apiVersion: v1
kind: Service
metadata:
  name: main_devops_app
  namespace: test_env
spec:
  type: LoadBalancer
  selector:
    app: main_devops_app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP