name: ci_app_build.yaml
on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read
  
jobs:
  acr_push:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          aws-region: eu-north-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get required env variables
        id: get-vars
        working-directory: terraform
        run: |
          echo "ecr_repo_name=$(terraform output -raw ecr_repo_name)" >> "$GITHUB_OUTPUT"
          echo "cluster_name=$(terraform output -raw cluster_name)" >> "$GITHUB_OUTPUT"
          echo "region=$(terraform output -raw region)" >> "$GITHUB_OUTPUT"
      
      - name: Build, tag, and push docker image to Amazon ECR
        working-directory: app
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ steps.get-vars.outputs.ecr_repo_name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Deploy to EKS Cluster
        working-directory: k8s
        env:
          CLUSTER_NAME: ${{ steps.get-vars.outputs.cluster_name }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ steps.get-vars.outputs.ecr_repo_name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          export IMAGE="$REGISTRY/$REPOSITORY:$IMAGE_TAG"
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION
          kubectl apply -f "namespace.yaml"
          envsubst '${IMAGE}' < deployment.yaml | kubectl apply -f -
          kubectl apply -f "deployment.yaml"
          kubectl apply -f "service.yaml"
          kubectl apply -f "EC2NodeClass.yaml"
          kubectl apply -f "NodePool.yaml"
          kubectl rollout status deployment/main-devops-app -n test --timeout=300s
    