name: Main pipeline with OIDC auth

on:
  workflow_dispatch: 
permissions: 
  id-token: write
  contents: read

jobs:
  provision_infra:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}

      - run: terraform init
        working-directory: terraform

      - run: terraform apply -auto-approve -lock-timeout=60s
        working-directory: terraform

      - name: Get K8s cluster name from TF Output
        id: tf_output
        run: |
          echo "cluster_name=$(terraform output -raw cluster_name)" >> "$GITHUB_OUTPUT"
          
      - name: Create Karpenter EC2NodeClass and NodePool
        run:  |
         aws eks update-kubeconfig --name ${{ steps.tf_output.outputs.cluster_name }} --region eu-north-1
         kubectl apply -f EC2NodeClass.yaml
         kubectl apply -f NodePool
        working-directory: k8s


          